server:
  port: 8081

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: service-hi
        uri: lb://SERVICE-HI
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
  zipkin:
    base-url: http://localhost:9411
  devtools:
    restart:
      enabled: true
      addtional-paths: src/main/java

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




