server:
  port: 8762

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
  devtools:
    restart:
      enabled: true
      addtional-paths: src/main/java

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'


